// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD056BrsykO8NiL-sLyyg-nWjicGGHKtOQ',
    appId: '1:246901202538:android:f79188473bc743d8b37413',
    messagingSenderId: '246901202538',
    projectId: 'dropit-nepal',
    storageBucket: 'dropit-nepal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9kIDBBlzNJiPEX6sHDuBSpEVn-zRAXk',
    appId: '1:246901202538:ios:4cb2585e0e3fb1a6b37413',
    messagingSenderId: '246901202538',
    projectId: 'dropit-nepal',
    storageBucket: 'dropit-nepal.firebasestorage.app',
    iosBundleId: 'com.example.packer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEUgVuiCW7ZwQL3Xf-p72-eFbLvRTOy0',
    appId: '1:45190832000:ios:05f1bc469409ecc730eb65',
    messagingSenderId: '45190832000',
    projectId: 'yole-44303',
    storageBucket: 'yole-44303.appspot.com',
    iosBundleId: 'com.example.packer',
  );

}